Repository BYU-Bazel/bazel-ls, pull requests merged in 2021-04, with the labels that each got.

#174 fixed label syntax
  examples/py_parser_paths/@baz/BUILD
  examples/py_parser_paths/@baz/nothing.py
  examples/py_parser_paths/BUILD
  server/src/main/java/server/bazel/interp/Label.java
  server/src/test/java/server/bazel/interp/LabelTest.java
Labels: bug

#175 Fix CodeLens Bugs
  server/src/main/java/server/commands/CommandProvider.java
  server/src/main/java/server/formatting/FormattingProvider.java
Labels: bug, deliverable, feature, prioritized

#176 Fix label path resolve and add config for codelens
  client_vscode/package.json
  server/src/main/java/server/BazelServices.java
  server/src/main/java/server/bazel/interp/Label.java
  server/src/main/java/server/commands/CommandProvider.java
  server/src/main/java/server/doclink/DocLinkProvider.java
  server/src/main/java/server/workspace/ExtensionConfig.java
Labels: bug, deliverable
