Repository BYU-Bazel/bazel-ls, pull requests merged in 2021-03, with the labels that each got.

#138 Users are now notified of Parsing errors
  server/src/main/java/server/BUILD
  server/src/main/java/server/BazelLanguageServer.java
  server/src/main/java/server/BazelServices.java
  server/src/main/java/server/workspace/Workspace.java
  server/src/test/java/server/workspace/WorkspaceTest.java
Labels: bug

#135 Trigger Diagnostics when file is opened
  server/src/main/java/server/BazelServices.java
Labels: bug

#150 setup ci for java8
  scripts/build.sh
Labels: bug

#151 Remove logging
  server/src/main/java/server/BazelLanguageServer.java
  server/src/main/resources/log4j2.xml
Labels: bug

#153 added sync capabilities
  client_vscode/package.json
  server/src/main/java/server/BazelLanguageServer.java
  server/src/main/java/server/BazelServices.java
  server/src/main/java/server/commands/AllCommands.java
  server/src/main/java/server/commands/BUILD
  server/src/main/java/server/commands/CommandProvider.java
  server/src/main/java/server/workspace/ExtensionConfig.java
  server/src/main/java/server/workspace/Workspace.java
  server/src/test/java/server/workspace/WorkspaceTest.java
Labels: deliverable, feature

#154 Duplicate deps
  server/src/main/java/server/diagnostics/DiagnosticCodes.java
  server/src/main/java/server/diagnostics/DiagnosticsProvider.java
Labels: deliverable

#159 Fix index out of bounds errors and target not found errors.
  client_vscode/src/main/extension.ts
  server/src/main/java/server/codelens/CodeLensProvider.java
Labels: bug

#160 example test cases
  .gitignore
  examples/py_parser_paths/BUILD
  examples/py_parser_paths/test/BUILD
  examples/py_parser_paths/test/number_test.py
  examples/py_parser_paths/test/string_test.py
Labels: testing
